# Generated by Django 2.2.27 on 2022-04-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220403_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='content',
        ),
        migrations.RemoveField(
            model_name='words',
            name='created',
        ),
    ]
