version: '3'
services:
    app:
        build:
            context: ./docker/construct_app      # Dockerfile保存場所
            dockerfile: Dockerfile-app    # Dockerfileファイル名
        container_name: sample-a
        image: node-app                  # イメージ名
        container_name: n-app         # コンテナ名
        ports:                          # ポート接続
            - 8882:8882
        volumes:                        # mount workdir
            - ./app:/src
        command: [sh, -c, npm install && npm run server]
        tty: true
        depends_on:
            - db
        links:
            - db
    db:
        container_name: sample-b
        image: postgres:13-alpine
        container_name: "test-postgres-db"
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: yama
            POSTGRES_USER: yama
            POSTGRES_DB: hello_database
            TZ: Asia/Tokyo
        volumes:
            - ./sql:/docker-entrypoint-initdb.d/
            - ./db/pgsql-data:/var/lib/postgresql/data
        working_dir: /src/